name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
 

    - name: Build Docker image
      run: |

       docker pull rupali1520/cockpit-frontend:prod
       docker tag rupali1520/cockpit-frontend:prod rupali1520/cockpit-frontend-archived:latest

       docker build -t rupali1520/cockpit-frontend:prod .

    - name: Log in to Docker Hub 
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
       docker push rupali1520/cockpit-frontend:prod
       docker push rupali1520/cockpit-frontend-archived:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build


    steps:
    - name: Install SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo docker pull rupali1520/cockpit-backend:prod
          sudo docker stop cockpit-frontend
          sudo docker rm -f cockpit-frontend
          sudo docker run -dp 4200:4200 --name cockpit-frontend rupali1520/cockpit-frontend:prod
