name: Shahenvaz GKE pipeline

on:
  push:
    branches: ['main']
    paths: ['src/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
 

    - name: Build Docker image
      run: |
       docker build -t shahenvaz7/angularfrontend:$GITHUB_RUN_ID .
       echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
       docker push shahenvaz7/angularfrontend:$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest

    needs: build


    steps:
    - name: deploy to GKE
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: $PROJECT_ID
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: ${{ secrets.REGION }}
      with:
        args: set image -f frontend_deployment.yaml angular-frontend=shahenvaz7/angularfrontend:$GITHUB_RUN_ID
